### ISSUE TITLE
NAME in Makefile.PL is invalid

### ISSUE THREAD

**Issue by miyagawa** [rjbs/Role-Identifiable#3]
The Makefile.PL in this distribution has this line:

https://metacpan.org/release/RJBS/Role-Identifiable-0.007/source/Makefile.PL#L21
```
  "NAME" => "Role::Identifiable",
```

which refers to a package that doesn't exist.

https://metacpan.org/pod/ExtUtils::MakeMaker#NAME1
NAME has to be a valid module for various toolchain metadata to be valid (MYMETA etc). 

Since this dist is dzil based, here's how the same issue has been fixed in LWP recently:
https://github.com/libwww-perl/libwww-perl/pull/413

**Comment by rjbs** [comment]
I have released Role-Identifiable-0.008.tar.gz which just goes ahead and adds a Role::Identifiable.  Hopefully that's all that's needed?

**Comment by miyagawa** [comment]
Yep, that also fixes the issue :)
